name: Moodle Plugin CI

on:
  push:
  pull_request:
  schedule:
    - cron: "33 2 * * 1" # weekly, on Monday morning

jobs:
  ci:
    uses: ucsf-education/moodle-plugin-ci-reusable-workflow/.github/workflows/gha.yml@MOODLE_501_STABLE
